# Generated by Django 2.1.5 on 2019-04-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_id', models.IntegerField(default=0)),
                ('set_name', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=200)),
                ('definition', models.CharField(max_length=400)),
            ],
        ),
    ]
