# Generated by Django 2.1.5 on 2019-04-21 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
                ('definition', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cards',
            name='card_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BadQuizletApp.Sets'),
        ),
    ]
